[package]
name = "rosen-zcash-native-inspector"
version = "0.1.0"
edition = "2024"

[dependencies]
hex = "=0.4.3"
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.145"
zcash_primitives = { git = "https://github.com/zcash/librustzcash", rev = "5345dbe0cd6c7f2057e631a34a74dffa84ff1d48", default-features = false, features = ["std"] }
zcash_protocol = { git = "https://github.com/zcash/librustzcash", rev = "5345dbe0cd6c7f2057e631a34a74dffa84ff1d48", default-features = false }
zcash_script = { version = "=0.4.3", default-features = false, features = ["std"] }
zcash_transparent = { git = "https://github.com/zcash/librustzcash", rev = "5345dbe0cd6c7f2057e631a34a74dffa84ff1d48", default-features = false, features = ["std"] }
